CircleCIにテストを設定

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,31 +1,116 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/configuration-reference
 version: 2.1
 
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
-jobs:
-  say-hello:
-    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
-    docker:
-      # Specify the version you desire here
-      # See: https://circleci.com/developer/images/image/cimg/base
-      - image: cimg/base:current
+orbs:
+  ruby: circleci/ruby@2.1.4
+  node: circleci/node@5.2.0
 
-    # Add steps to the job
-    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
+executors:
+  jekyll-executor:
+    docker:
+      - image: cimg/ruby:3.4.5-node
+    working_directory: ~/repo
+
+jobs:
+  lint-html-scss:
+    executor: jekyll-executor
     steps:
-      # Checkout the code as the first step.
+      - checkout
+      - restore_cache:
+          name: Restore pnpm Package Cache
+          keys:
+            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
+      - run:
+          name: Setup pnpm package manager
+          command: |
+            # pnpmをスタンドアロンインストール（権限エラー回避）
+            wget -qO- https://get.pnpm.io/install.sh | env SHELL=/bin/bash PNPM_VERSION=10.14.0 sh -
+            echo 'export PNPM_HOME="/home/circleci/.local/share/pnpm"' >> $BASH_ENV
+            echo 'export PATH="$PNPM_HOME:$PATH"' >> $BASH_ENV
+            source $BASH_ENV
+            pnpm config set store-dir .pnpm-store
+      - run:
+          name: Install Node dependencies
+          command: |
+            pnpm install --no-frozen-lockfile
+      - save_cache:
+          name: Save pnpm Package Cache
+          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
+          paths:
+            - .pnpm-store
+      - run:
+          name: Run SCSS linter
+          command: pnpm run lint:scss
+      - ruby/install-deps:
+          bundler-version: '2.6.1'
+      - run:
+          name: Build Jekyll site
+          command: bundle exec jekyll build
+      - run:
+          name: Run HTML linter
+          command: pnpm run lint:html
+
+  build-jekyll:
+    executor: jekyll-executor
+    steps:
+      - checkout
+      - ruby/install-deps:
+          bundler-version: '2.6.1'
+      - run:
+          name: Jekyll build
+          command: bundle exec jekyll build --verbose
+      - run:
+          name: Check build output
+          command: |
+            if [ ! -d "_site" ]; then
+              echo "Build failed: _site directory not found"
+              exit 1
+            fi
+            echo "Build successful! Site files:"
+            ls -la _site/
+      - persist_to_workspace:
+          root: ~/repo
+          paths:
+            - _site
+
+  security-scan:
+    docker:
+      - image: cimg/ruby:3.4.5
+    steps:
       - checkout
       - run:
-          name: "Say hello"
-          command: "echo Hello, World!"
+          name: Install bundler-audit
+          command: gem install bundler-audit
+      - run:
+          name: Update vulnerability database
+          command: bundle audit update
+      - run:
+          name: Check for vulnerable dependencies
+          command: bundle audit check
 
-# Orchestrate jobs using workflows
-# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
 workflows:
-  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
-    # Inside the workflow, you define the jobs you want to run.
+  version: 2
+  test-and-build:
     jobs:
-      - say-hello
+      - lint-html-scss:
+          filters:
+            branches:
+              ignore: gh-pages
+      - build-jekyll:
+          filters:
+            branches:
+              ignore: gh-pages
+      - security-scan:
+          filters:
+            branches:
+              ignore: gh-pages
+
+  nightly-security-check:
+    triggers:
+      - schedule:
+          cron: '0 0 * * *'
+          filters:
+            branches:
+              only:
+                - main
+    jobs:
+      - security-scan
